services:
  prod_app: &prod
    build:
      target: prod
    ports:
      - 3000:3000
    depends_on:
      - db
    tty: true
    stdin_open: true

  prod_scheduler:
    <<: *prod
    build:
      target: prod_scheduler
    ports: []

  app: &app
    <<: *prod
    build:
      target: dev
    volumes:
      - ./:/usr/src/
    environment:
      - CONFIG_PATH=./config/dev.yaml

  scheduler:
    <<: *app
    command: go run ./cmd/scheduler/scheduler.go
    ports: []

  db:
    image: postgres:18.0-alpine3.22
    environment:
      POSTGRES_USER: pguser
      POSTGRES_PASSWORD: pgpassword
    volumes:
      - pgdata:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    restart: always

volumes:
  pgdata:
