services:
  app:
    build:
      target: dev
      context: ./
      dockerfile: ./Dockerfile
    command: ./server
    ports:
      - 3000:3000
    depends_on:
      - db
    env_file:
      - .env
    tty: true
    stdin_open: true

  db:
    image: postgres:18.0-alpine3.22
    environment:
      POSTGRES_USER: pguser
      POSTGRES_PASSWORD: pgpassword
    volumes:
      - pgdata:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    restart: always

volumes:
  pgdata:
