services:
  app: &app
    build:
      target: prod
    ports:
      - 3000:3000
    depends_on:
      - db
    tty: true
    stdin_open: true

  backjobs:
    <<: *app
    build:
      target: prod_backjobs
    ports: []

  consumer:
    <<: *app
    build:
      target: prod_consumer
    ports: []
    depends_on:
      - kafka

  db:
    image: postgres:18.0-alpine3.22
    environment:
      POSTGRES_USER: pguser
      POSTGRES_PASSWORD: pgpassword
    volumes:
      - pgdata:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    restart: always

  zookeeper:
    image: confluentinc/cp-zookeeper:5.4.0
    hostname: zookeeper
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:5.3.0
    hostname: kafka
    container_name: kafka
    environment:
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka1:9092,PLAINTEXT_HOST://localhost:19092
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_BROKER_ID: 1
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_CONFLUENT_LICENSE_TOPIC_REPLICATION_FACTOR: 1
    ports:
      - 19092:19092
    depends_on:
      - zookeeper
    healthcheck:
      test: nc -z localhost 9092 || exit -1
      interval: 5s
      timeout: 10s
      retries: 10

volumes:
  pgdata:
